name: Markdown Lint

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run markdownlint
        uses: davidanson/markdownlint-cli2-action@v19
        with:
          args: 'README.md'
          config: 'config/readme.markdownlint.jsonc'
